import { readFileSync, writeFileSync } from "fs"

import { Command } from "commander"
import { yaml2interface } from "ts2interface"

// 配置相关指令
export function configCommand(): Command {
	const config = new Command("config")

	config
		.argument("<init>", "根据项目内的配置文件初始化数据结构")
		.description("更新项目配置")
		.option(
			"-i, --input",
			"指定配置文件访问路径，默认为：./setting.default.yml",
			"./setting.default.yml"
		)
		.option(
			"-o, --output",
			"指定输出结构文件路径，默认为：./src/config/setting.ts",
			"./src/config/setting.ts"
		)
		.action(() => {
			const input = config.opts()["input"]
			const output = config.opts()["output"]
			const content = readFileSync(input)
			let structContent = yaml2interface(content.toString(), {
				rootName: "Setting",
				indent: 4,
				semi: false,
				useTab: true,
			})

			structContent =
				"// Code generated by ts2interface. DO NOT EDIT.\n\n" +
				structContent

			writeFileSync(output, structContent)
			console.log("数据结构初始化完成")
		})

	return config
}
